# Introduction {-#intro}

Econometrics as a sub-field of Economics is primarily concerned with statistical analysis of economic data.  Consider an important  economic relationship, namely, the effect of education on labor market wage. Economic theory suggests higher education should lead to greater wages. Econometrics provides a toolkit for empirically testing this relationship using real world labor market data. Note that there are two distinct analyses one maybe interested in this context:

1. What is the causal effect of education on wages? 

2. Given data on education, what can we say about wages?

Before answering these questions, we need to consider several ancillary issues that are especially unique to economic relationships. For example, what kind of data can be used to answer above-mentioned questions? What are some of the specification issues we must account for in estimating the effect of education on wages?  The key issue is that although economic theory provides a qualitative basis for an economic relationship, it is often a poor quantitative guide. For instance, economic theory will tell us that higher education leads to greater wages but does not tell us by how much or whether such a relation is linear or non-linear in nature. 

An important distinction which is often not emphasized in most Econometrics textbooks is between two main purposes of economic analysis:

1. Explanatory analysis: here the goal is to obtain a causal effect of an **independent or explanatory** variable on a **dependent or outcome** variable of interest. In the context of our economic example, we can ask the following question: what is the effect of education on wages? Implicit here is an assumption that education has a causal effect on wages of an individual. This is inherently a quantitative question and we need a numerical answer to this question. Further, because in practice we use sample data for answering such questions, use of different samples will provide different estimates of the effect of education on wages. As a result we need to also provide some measure of how precise our numerical estimate of the causal effect is.

2. Predictive analysis: here the goal is to obtain an accurate forecast or prediction of future (new) values of the dependent variable, given data on independent variable(s). For instance, if we are given data on education what can we say about expected wages? An answer to this question does not require a causal relationship between education and wages. The goal of predictive analysis is to forecast the dependent variable for new observations given data on the independent variable(s). These new observations could be across sample units (e.g., individuals, firms, countries) or over time (e.g., week, month, year). A more common use of predictive analysis is to generate forecasts of the variable of interest over time. Such analysis can be done by only utilizing historical data on the dependent variable and/or by using historical data on other relevant variables. What is important is that a lack of causal relationship between variables does not necessarily reduce the forecast accuracy of a predictive model. 

Although the *classical regression model* is used for both types of analyses, it is important to distinguish between, for example, an attempt to tease out the causal effect of education on wages versus predicting wages based on education. Let us use two potential issues that one may face in this context to illustrate their differential treatment depending on whether our objective is to obtain a causal effect of education on wages or predict wages using data on education.

a. It is reasonable to argue that an individual's innate ability can simultaneously affect both her education and wages. However, because it is very difficult to measure innate ability, we exclude it from our analysis. 

b. It is possible that dispersion in wages decreases in education so that education provides a more accurate prediction of wages for observations with higher level educations when compared to those with lower level of education.  


If our goal is to obtain a causal effect of education on wages, excluding innate ability will confound the effect of education on wages. The idea here is that individuals with higher innate ability are also more likely to obtain higher education. Hence, if we exclude ability from our model, we cannot tease out the causal effect of education on wages because only part of the estimated effect from such a model can be attributed to education. This is the *omitted variable* problem that constitutes one of the most important obstacles in causal analysis is the possibility of omitting relevant explanatory variables from. Going back to our example, any causal analysis of education on wages needs to devote substantial attention to such confounding effects of omitted variables. On the other hand, the issue of wage dispersion being systematically affected by education can only affect the precision of the estimator. Hence, it is commonplace to account for such a pattern by simply scaling the standard errors of the estimated coefficient of education appropriately.

In contrast, if our goal is to predict wages based on education, lack of data on innate ability and the consequent non-casual interpretation of estimator is not important. As long as education provides useful information about wages in data it will help improve the forecast of wages. However, a greater emphasis in this case needs to placed on the second issue of wage dispersion decreasing in education. Such a pattern in data is valuable for improving forecast accuracy and must be explicitly modeled along with the effect of education on wages for obtaining a more accurate forecast. 

The aforementioned distinction between predictive and explanatory analyses is a recurring theme in this textbook. For every topic covered in the text, I will attempt to establish a link between the main issues and how their relevance/importance will vary depending on whether our goal is to predict an economic variable or explain the causal factors that determine this variable.